# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc3b75afdf8c79265dc898378916dea14b4338ca140218da8dd58d6a5432aa87c016330661d82e574380fe65f95744b2759ecf3b9d4df244d8a8c478711140c5

test:
  secret_key_base: 6c1ed1a19b71ce294b5b4dd0dd7b1d6db5fc974dda18b7c65e39e89eb8d895c4539f558656c632229232d8c4879e39f74eb70aaf336c40c88c1d0dd2edf52311

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
